#!/usr/bin/perl
# $Id: change_password 428 2006-08-30 02:00:57Z corrupt $
use lib('../../lib');

#
# change_password
#

use vars qw($this_tool);

BEGIN {

    use BadNews::ToolRegistry::Tool;

    $this_tool = BadNews::ToolRegistry::Tool->new(
        tool_title          =>          'Change Your Password',
        tool_name           =>          'change_password',
        description         =>          'Change your BadNews system password',
        menu_position       =>          '_top, System',
        sufficient_flags    =>          ['s', 'a', 'u']
    );

    if ($ARGV[0] eq "register") {
        print $this_tool->registration;
        exit();
    }

}

use Template;
use BadNews;
use BadNews::Session;
use BadNews::Author;
use CGI;

my $q = new CGI;
my $bn = BadNews->new;
my $c = $bn->c;

my $tmpl = Template->new({INCLUDE_PATH   =>      $c->CMS_PATH . "/templates",
                         PRE_PROCESS    =>      [qw(header.tt2 footer.tt2 tool_head_foot.tt2)],
                         TRIM           =>      1});

my $error = { change_password       =>      '&nbsp;' };

my $cpass = $q->param('cpass');
my $p1 = $q->param('pass1');
my $p2 = $q->param('pass2');

my $session_id = $q->cookie('bnauth');

if ($session_id) {
    my $session = BadNews::Session->new(session_id => $session_id);
    if ($session) {
        if ($cpass && $p1 && $p2) {
            my $author = BadNews::Author->open_by_name($session->user);
            if ($author) {
                if ($author->authenticate($cpass)) {
                    if ($p1 eq $p2) {
                        $author->change_pass($p1);
                        $bn->log($session->user, 'change_password');
                        print $q->header();
                        $tmpl->process('t_message.tt2', {   title       =>      'Change Your Password',
                                                            error       =>      $error,
                                                            self        =>      'change_password',
                                                            tool_name   =>      'Change Your Password',
                                                            tool_icon   =>      '../../theme_images/control_panel/04changepass.gif',
                                                            message     =>      'Password changed successfully.'});
                        exit();
                    } else {
                        $error->{change_password} = "Passwords don't match!";
                    }
                } else {
                    $error->{change_password} = "Authentication failed.";
                }
            } else {
                $error->{change_password} = "Strange error: No such user.";
            }
        }
        print $q->header();
        $tmpl->process('change_password.tt2', { title     =>      'Change Your Password',
                                          error     =>      $error,
                                          self      =>      'change_password',
                                          tool_name =>      'Change Your Password',
                                          tool_icon =>      '../../theme_images/control_panel/04changepass.gif' });
        exit();
    } else {
        print $q->redirect('tools/login?logout=1');
        exit();
    }
} else {
    print $q->redirect('tools/login');
    exit();
}
