#!/usr/bin/perl
# $Id: delete_author 428 2006-08-30 02:00:57Z corrupt $
use lib('../../lib');

#
# delete author
#

use vars qw($this_tool);

BEGIN {

    use BadNews::ToolRegistry::Tool;

    $this_tool = BadNews::ToolRegistry::Tool->new(
        tool_title          =>          'Delete An Author',
        tool_name           =>          'delete_author',
        description         =>          'Delete an author enabled user from BadNews',
        menu_position       =>          '_none',
        sufficient_flags    =>          ['s']
    );

    if ($ARGV[0] eq "register") {
        print $this_tool->registration;
        exit();
    }

}

use Template;
use BadNews;
use BadNews::Session;
use BadNews::Author;

my $q = new CGI;
my $bn = BadNews->new;
my $c = $bn->c;

my $tmpl = Template->new({INCLUDE_PATH   =>      $c->CMS_PATH . "/templates",
                         PRE_PROCESS    =>      [qw(header.tt2 footer.tt2 tool_head_foot.tt2)],
                         TRIM           =>      1});

my $error = {};
my $id = $q->param('id');
my $confirm = $q->param('confirm');

my $session_id = $q->cookie('bnauth');

if ($session_id) {
    my $session = BadNews::Session->new(session_id => $session_id);
    if ($session) {
        my $autho = $session->bnuser;
        unless ($autho->has_flag('a')) {
            print $q->header();
            $tmpl->process('t_message.tt2', {   title           =>          'Access Denied',
                                                self            =>          'delete_author',
                                                message         =>          'Author: ' . $session->user . ' does not have the privileges required to access this tool.',
                                                tool_name       =>          'Delete An Author - Access Denied',
                                                tool_icon       =>          '../../theme_images/control_panel/03deleteauthor.gif'});
            exit();
        }
        my $author = BadNews::Author->open($id);
        if ($author) {
            if ($confirm) {
                my $un = $author->username;
                $author->delete;
                $bn->log($session->user, 'delete_author', $un);
                print $q->header();
                $tmpl->process('t_message.tt2', {   title       =>      "Author $un deleted successfully!",
                                                    error       =>      $error,
                                                    tool_name   =>      'Delete An Author',
                                                    tool_icon   =>      '../../theme_images/control_panel/03deleteauthor.gif',
                                                    message     =>      "Author $un has been permanently removed from the author database." });
            } else {
                print $q->header();
                $tmpl->process('t_prompt.tt2',  {   title       =>      'Delete Author Confirm',
                                                    error       =>      $error,
                                                    tool_name   =>      'Delete An Author',
                                                    no_url      =>      'javascript:window.close();',
                                                    yes_url     =>      'delete_author?id=' . $author->id . '&confirm=1',
                                                    tool_icon   =>      '../../theme_images/control_panel/03deleteauthor.gif',
                                                    question    =>      'Are you sure you want to remove the author: ' . $author->username . '?'});
            }
        } else {
            print $q->header();
            $tmpl->process('t_generic.tt2', {       title       =>      'Delete An Author',
                                                    prompt      =>      'Please enter the author id:',
                                                    fetch       =>      'id',
                                                    action      =>      'delete_author',
                                                    error       =>      $error,
                                                    tool_name   =>      'Delete An Author',
                                                    tool_icon   =>      '../../theme_images/control_panel/03deleteauthor.gif' });
        }
        exit();
    } else {
        print $q->redirect('tools/login?logout=1');
        exit();
    }
} else {
    print $q->redirect('tools/login');
    exit();
}
