#!/usr/bin/perl
# $Id: list_files 428 2006-08-30 02:00:57Z corrupt $
use lib('../../lib');

#
# list files
#

use vars qw($this_tool);

BEGIN {

    use BadNews::ToolRegistry::Tool;

    $this_tool = BadNews::ToolRegistry::Tool->new(
                tool_title          =>          'List Files',
                tool_name           =>          'list_files',
                description         =>          'List uploaded files',
                menu_position       =>          '_top, Files',
                sufficient_flags    =>          ['s', 'a']
            );

    if ($ARGV[0] eq "register") {
        print $this_tool->registration;
        exit();
    }

}

use Template;
use BadNews;
use BadNews::Session;
use BadNews::File::Search;
use CGI;

my $q = new CGI;
my $bn = BadNews->new;
my $c = $bn->c;

my $tmpl = Template->new({INCLUDE_PATH   =>     $c->CMS_PATH . "/templates",
                         PRE_PROCESS    =>      [qw(header.tt2 footer.tt2 tool_head_foot.tt2)],
                         TRIM           =>      1});

my $search = BadNews::File::Search->new(all  =>  1);
my $error = {};

my $session_id = $q->cookie('bnauth');

if ($session_id) {
    my $session = BadNews::Session->new(session_id => $session_id);
    if ($session) {
        print $q->header();
        $tmpl->process('list_files.tt2', { title     =>      'List Files',
                                          error     =>      $error,
                                          search    =>      $search,
                                          tool_name =>      'List Files',
                                          tool_icon =>      '../../theme_images/control_panel/02listfiles.gif' });
        exit();
    } else {
        print $q->redirect('tools/login?logout=1');
        exit();
    }
} else {
    print $q->redirect('tools/login');
    exit();
}
