#!/usr/bin/perl
# $Id: manage_art_comments 428 2006-08-30 02:00:57Z corrupt $
use lib('../../lib');

#
# manage event types!
#

use vars qw($this_tool);

BEGIN {

    use BadNews::ToolRegistry::Tool;

    $this_tool = BadNews::ToolRegistry::Tool->new(
                tool_title          =>          'Manage Article Comments',
                tool_name           =>          'manage_art_comments',
                description         =>          'Manage (mostly delete) comments left by users on articles',
                menu_position       =>          '_top, Articles',
                sufficient_flags    =>          ['s', 'a']
            );

    if ($ARGV[0] eq "register") {
        print $this_tool->registration;
        exit();
    }

}

use Template;
use BadNews;
use BadNews::Session;
use BadNews::ArticleInterface;
use BadNews::Article::Comment;
use CGI;

my $q = new CGI;
my $bn = BadNews->new;
my $c = $bn->c;

my $tmpl = Template->new({INCLUDE_PATH   =>     $c->CMS_PATH . "/templates",
                         PRE_PROCESS    =>      [qw(header.tt2 footer.tt2 tool_head_foot.tt2)],
                         TRIM           =>      1});

my $ai = BadNews::ArticleInterface->new();
my $error = {};

# get function
my $func = $q->param('func');

my $session_id = $q->cookie('bnauth');

if ($session_id) {
    my $session = BadNews::Session->new(session_id => $session_id);
    if ($session) {
        if ($func eq "delete") {
            foreach my $param ($q->Vars) {
                if ($param =~ /^comment(\d+)$/) {
                    print $q->header();
                    my $comment = BadNews::Article::Comment->open($1);
                    my $comment_user = $comment->name;
                    if ($comment->delete) {
                        $bn->log($session->user, 'delete_article_comment', "comment by user $comment_user");
                    }
                }
            }
        }
        print $q->header();
        $tmpl->process('manage_art_comments.tt2', { title     =>      'Manage Article Comments',
                                          error     =>      $error,
                                          ai        =>      $ai,
                                          tool_name =>      'Manage Article Comments',
                                          tool_icon =>      '../../theme_images/control_panel/04managearticle.gif' });
        exit();
    } else {
        print $q->redirect('tools/login?logout=1');
        exit();
    }
} else {
    print $q->redirect('tools/login');
    exit();
}
